package aplicacion.modelo.dominio;
// Generated 14/06/2018 11:42:48 by Hibernate Tools 4.3.1



/**
 * ButacaCartelera generated by hbm2java
 */
public class ButacaCartelera  implements java.io.Serializable {


     private Integer bcCodigo;
     private String bcIdentificadorButaca;
     private boolean bcDisponible;
     private boolean bcEstado;
     private Cartelera carteleras;

    public ButacaCartelera() {
    }

    public ButacaCartelera(String bcIdentificadorButaca, boolean bcDisponible, boolean bcEstado, Cartelera carteleras) {
        this.bcIdentificadorButaca = bcIdentificadorButaca;
        this.bcDisponible = bcDisponible;
        this.bcEstado = bcEstado;
        this.carteleras = carteleras;
    }

 
    public Integer getBcCodigo() {
        return this.bcCodigo;
    }
    
    public void setBcCodigo(Integer bcCodigo) {
        this.bcCodigo = bcCodigo;
    }
    public String getBcIdentificadorButaca() {
        return this.bcIdentificadorButaca;
    }
    
    public void setBcIdentificadorButaca(String bcIdentificadorButaca) {
        this.bcIdentificadorButaca = bcIdentificadorButaca;
    }
    public boolean isBcDisponible() {
        return this.bcDisponible;
    }
    
    public void setBcDisponible(boolean bcDisponible) {
        this.bcDisponible = bcDisponible;
    }
    public boolean isBcEstado() {
        return this.bcEstado;
    }
    
    public void setBcEstado(boolean bcEstado) {
        this.bcEstado = bcEstado;
    }

    /**
     * @return the carteleras
     */
    public Cartelera getCarteleras() {
        return carteleras;
    }

    /**
     * @param carteleras the carteleras to set
     */
    public void setCarteleras(Cartelera carteleras) {
        this.carteleras = carteleras;
    }




}


