package aplicacion.modelo.dominio;
// Generated 14/06/2018 11:42:48 by Hibernate Tools 4.3.1



/**
 * Butaca generated by hbm2java
 */
public class Butaca  implements java.io.Serializable {


     private Integer butCodigo;
     private String butIdentificador;
     private boolean butEstado;
     private Sala salas;

    public Butaca() {
    }

    public Butaca(String butIdentificador, boolean butEstado, Sala salas) {
        this.butIdentificador = butIdentificador;
        this.butEstado = butEstado;
        this.salas = salas;
    }
    


   
    public Integer getButCodigo() {
        return this.butCodigo;
    }
    
    public void setButCodigo(Integer butCodigo) {
        this.butCodigo = butCodigo;
    }
    public String getButIdentificador() {
        return this.butIdentificador;
    }
    
    public void setButIdentificador(String butIdentificador) {
        this.butIdentificador = butIdentificador;
    }
    public boolean isButEstado() {
        return this.butEstado;
    }
    
    public void setButEstado(boolean butEstado) {
        this.butEstado = butEstado;
    }

    /**
     * @return the salas
     */
    public Sala getSalas() {
        return salas;
    }

    /**
     * @param salas the salas to set
     */
    public void setSalas(Sala salas) {
        this.salas = salas;
    }


}


