package aplicacion.modelo.dominio;
// Generated 14/06/2018 11:42:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 *Cartelera generated by hbm2java
 */
public class Cartelera  implements java.io.Serializable {


     private Integer carCodigo;
     private Pelicula peliculas;
     private Sala salas;
     private Date carFecha;
     private String carHorario;
     private double carPrecio;
     private boolean carEstado;

    public Cartelera() {
    }

    public Cartelera(Pelicula peliculas, Sala salas, Date carFecha, String carHorario, double carPrecio, boolean carEstado) {
        this.peliculas = peliculas;
        this.salas = salas;
        this.carFecha = carFecha;
        this.carHorario = carHorario;
        this.carPrecio = carPrecio;
        this.carEstado = carEstado;
    }

    
   
    public Integer getCarCodigo() {
        return this.carCodigo;
    }
    
    public void setCarCodigo(Integer carCodigo) {
        this.carCodigo = carCodigo;
    }
    public Date getCarFecha() {
        return this.carFecha;
    }
    
    public void setCarFecha(Date carFecha) {
        this.carFecha = carFecha;
    }
    public String getCarHorario() {
        return this.carHorario;
    }
    
    public void setCarHorario(String carHorario) {
        this.carHorario = carHorario;
    }
    public double getCarPrecio() {
        return this.carPrecio;
    }
    
    public void setCarPrecio(double carPrecio) {
        this.carPrecio = carPrecio;
    }
    public boolean isCarEstado() {
        return this.carEstado;
    }
    
    public void setCarEstado(boolean carEstado) {
        this.carEstado = carEstado;
    }

    /**
     * @return the peliculas
     */
    public Pelicula getPeliculas() {
        return peliculas;
    }

    /**
     * @param peliculas the peliculas to set
     */
    public void setPeliculas(Pelicula peliculas) {
        this.peliculas = peliculas;
    }

    /**
     * @return the salas
     */
    public Sala getSalas() {
        return salas;
    }

    /**
     * @param salas the salas to set
     */
    public void setSalas(Sala salas) {
        this.salas = salas;
    }




}


