package aplicacion.modelo.dominio;
// Generated 14/06/2018 11:42:48 by Hibernate Tools 4.3.1



/**
 * PelCla generated by hbm2java
 */
public class PelCla  implements java.io.Serializable {


     private Integer pcCodigo;
     private Pelicula peliculas;
     private boolean pcEstado;
     private Clasificacion clasificaciones;

    public PelCla() {
    }

    public PelCla(Pelicula peliculas, boolean pcEstado, Clasificacion clasificaciones) {
        this.peliculas = peliculas;
        this.pcEstado = pcEstado;
        this.clasificaciones = clasificaciones;
    }


   
    public Integer getPcCodigo() {
        return this.pcCodigo;
    }
    
    public void setPcCodigo(Integer pcCodigo) {
        this.pcCodigo = pcCodigo;
    }
    public Pelicula getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Pelicula peliculas) {
        this.peliculas = peliculas;
    }
    public boolean isPcEstado() {
        return this.pcEstado;
    }
    
    public void setPcEstado(boolean pcEstado) {
        this.pcEstado = pcEstado;
    }

    /**
     * @return the clasificaciones
     */
    public Clasificacion getClasificaciones() {
        return clasificaciones;
    }

    /**
     * @param clasificaciones the clasificaciones to set
     */
    public void setClasificaciones(Clasificacion clasificaciones) {
        this.clasificaciones = clasificaciones;
    }




}


