package aplicacion.modelo.dominio;
// Generated 14/06/2018 11:42:48 by Hibernate Tools 4.3.1



/**
 * PelDir generated by hbm2java
 */
public class PelDir  implements java.io.Serializable {


     private Integer pdCodigo;
     private Pelicula peliculas;
     private Director directores;
     private boolean pdEstado;

    public PelDir() {
    }

    public PelDir(Pelicula peliculas, Director directores, boolean pdEstado) {
        this.peliculas = peliculas;
        this.directores = directores;
        this.pdEstado = pdEstado;
    }


   
    public Integer getPdCodigo() {
        return this.pdCodigo;
    }
    
    public void setPdCodigo(Integer pdCodigo) {
        this.pdCodigo = pdCodigo;
    }
    public Pelicula getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Pelicula peliculas) {
        this.peliculas = peliculas;
    }
    public boolean isPdEstado() {
        return this.pdEstado;
    }
    
    public void setPdEstado(boolean pdEstado) {
        this.pdEstado = pdEstado;
    }

    /**
     * @return the directores
     */
    public Director getDirectores() {
        return directores;
    }

    /**
     * @param directores the directores to set
     */
    public void setDirectores(Director directores) {
        this.directores = directores;
    }
    

}


