package aplicacion.modelo.dominio;
// Generated 14/06/2018 11:42:48 by Hibernate Tools 4.3.1



/**
 * PrecioCartelera generated by hbm2java
 */
public class PrecioCartelera  implements java.io.Serializable {


     private Integer preCodigo;
     private String preDescripcion;
     private double prePrecio;
     private int preCartelera;

    public PrecioCartelera() {
    }

    public PrecioCartelera(String preDescripcion, double prePrecio, int preCartelera) {
       this.preDescripcion = preDescripcion;
       this.prePrecio = prePrecio;
       this.preCartelera = preCartelera;
    }
   
    public Integer getPreCodigo() {
        return this.preCodigo;
    }
    
    public void setPreCodigo(Integer preCodigo) {
        this.preCodigo = preCodigo;
    }
    public String getPreDescripcion() {
        return this.preDescripcion;
    }
    
    public void setPreDescripcion(String preDescripcion) {
        this.preDescripcion = preDescripcion;
    }
    public double getPrePrecio() {
        return this.prePrecio;
    }
    
    public void setPrePrecio(double prePrecio) {
        this.prePrecio = prePrecio;
    }
    public int getPreCartelera() {
        return this.preCartelera;
    }
    
    public void setPreCartelera(int preCartelera) {
        this.preCartelera = preCartelera;
    }




}


